# Generated by Django 2.1 on 2018-09-15 18:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subadd', '0002_auto_20180911_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='time administered')),
                ('notes', models.CharField(max_length=160)),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subadd.Substance')),
            ],
        ),
    ]
