# Generated by Django 2.2.dev20180928135712 on 2018-11-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recadm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='dosage',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
    ]
