# Generated by Django 2.2.dev20180928135712 on 2019-01-13 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recadm', '0002_auto_20181111_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='user',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usage',
            name='notes',
            field=models.CharField(max_length=512),
        ),
    ]
