# Generated by Django 2.2.dev20180928135712 on 2019-07-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recadm', '0005_usualsuspect'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='valid_entry',
            field=models.BooleanField(default=True),
        ),
    ]
