# Generated by Django 2.2.dev20180928135712 on 2019-02-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navinfo',
            name='link_text',
            field=models.CharField(max_length=30),
        ),
    ]
