# Generated by Django 2.1 on 2018-09-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Substance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=40)),
                ('sci_name', models.CharField(max_length=60)),
                ('half_life', models.IntegerField()),
            ],
        ),
    ]
