# Generated by Django 2.1 on 2018-09-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subadd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='substance',
            name='active_half_life',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='substance',
            name='lipid_solubility',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='substance',
            name='half_life',
            field=models.IntegerField(default=16),
        ),
    ]
