# Generated by Django 2.2.dev20180928135712 on 2018-11-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subadd', '0002_auto_20180911_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substance',
            name='active_half_life',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
        migrations.AlterField(
            model_name='substance',
            name='half_life',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
    ]
