# Generated by Django 2.2.dev20180928135712 on 2019-01-14 11:55

from django.db import migrations, models
import lasttime.myglobals


class Migration(migrations.Migration):

    dependencies = [
        ('subadd', '0003_auto_20181111_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='substance',
            name='units',
            field=models.CharField(choices=[(lasttime.myglobals.Units('MCG'), 'mcg'), (lasttime.myglobals.Units('MG'), 'mg'), (lasttime.myglobals.Units('ML'), 'ml'), (lasttime.myglobals.Units('FL OZ'), 'fl oz'), (lasttime.myglobals.Units('TSP'), 'tsp')], default=lasttime.myglobals.Units('MG'), max_length=5),
        ),
    ]
