# Generated by Django 2.2.dev20180928135712 on 2019-01-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subadd', '0004_auto_20190114_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosageunit',
            name='abbreviation',
            field=models.CharField(max_length=5, verbose_name='unit abbreviation'),
        ),
        migrations.AlterField(
            model_name='dosageunit',
            name='description',
            field=models.CharField(max_length=20, verbose_name='unit description'),
        ),
    ]
