# Generated by Django 2.2.dev20180928135712 on 2019-04-30 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subadd', '0006_auto_20190114_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubstanceClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('desc', models.CharField(max_length=160)),
            ],
        ),
        migrations.AddField(
            model_name='substance',
            name='sub_class',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='subadd.SubstanceClass'),
        ),
    ]
