# Generated by Django 2.2.dev20180928135712 on 2019-05-01 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subadd', '0007_auto_20190430_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substance',
            name='common_name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='substance',
            name='sci_name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='substanceclass',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
