# Generated by Django 2.2.dev20180928135712 on 2019-01-20 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dox', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainHelpTopicDetails',
            new_name='MainHelpTopicDetail',
        ),
        migrations.RenameModel(
            old_name='SpecificViewTopicDetails',
            new_name='SpecificViewTopicDetail',
        ),
    ]
