# Generated by Django 2.2.dev20180928135712 on 2019-02-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dox', '0003_specificviewhelptopic_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificviewtopicdetail',
            name='sub_topic',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
